import re
from collections import Counter

class MarkdownFormatter:
    """Transforms structured page layout matrix extractions into clean Markdown files."""
    def __init__(self, structured_pages_data):
        # Accepts the list structure generated by the new PDFExtractor class
        self.pages_data = structured_pages_data
        self.median_font_size = self._calculate_global_median_font()

    def _calculate_global_median_font(self) -> float:
        """Finds the median body font size across the document to map headings accurately."""
        font_sizes = []
        if isinstance(self.pages_data, str):
            return 10.0 # Standard fallback value
            
        for page in self.pages_data:
            for block in page:
                for line in block:
                    font_sizes.append(round(line["size"], 1))
        
        if font_sizes:
            # Return the most frequent font size as the standard body text size
            return Counter(font_sizes).most_common(1)[0][0]
        return 10.0

    def format_text(self) -> str:
        """Compiles the structured document chunks into structured Markdown text."""
        if isinstance(self.pages_data, str):
            return self.pages_data # Return text directly if pre-formatted

        markdown_document_output = []

        # List detection regex for common bullet styles: •, -, *, 1., a)
        list_pattern = re.compile(r'^([\s\t]*)([•\-*]|\d+\.|\b[a-z]\))\s+(.*)$')

        for page in self.pages_data:
            for block in page:
                block_lines = []
                
                # --- PRE-PASS: DE-HYPHENATION & SOFT paragraph UNWRAPPING ---
                i = 0
                while i < len(block):
                    current_line = block[i]
                    current_text = current_line["text"].strip()
                    
                    # Check if the next line soft-wraps and continues the same paragraph
                    if i + 1 < len(block):
                        next_line = block[i + 1]
                        next_text = next_line["text"].strip()
                        
                        # Case A: Line ends with a hyphen and continues on the next line
                        if current_text.endswith("-") and next_text and next_text[0].islower():
                            current_text = current_text[:-1] + next_text
                            current_line["text"] = current_text
                            block.pop(i + 1)
                            continue
                        
                        # Case B: Paragraph text wrapping onto the next line
                        elif (not current_text[-1] in ['.', '!', '?', ':'] and 
                              next_text and next_text[0].islower() and 
                              not list_pattern.match(next_text) and
                              abs(current_line["size"] - next_line["size"]) < 0.5):
                            current_text = current_text + " " + next_text
                            current_line["text"] = current_text
                            block.pop(i + 1)
                            continue
                    
                    block_lines.append(current_line)
                    i += 1

                # --- HEADING & LIST CLASSIFICATION PASS ---
                block_output_strings = []
                for line in block_lines:
                    text = line["text"].strip()
                    size = line["size"]
                    is_bold = line["bold"]

                    # List Item Match
                    list_match = list_pattern.match(text)
                    
                    # Heading Depth Inference based on font size weights
                    if size > self.median_font_size + 6.0:
                        block_output_strings.append(f"\n# {text}\n")
                    elif size > self.median_font_size + 3.0:
                        block_output_strings.append(f"\n## {text}\n")
                    elif size > self.median_font_size + 0.5 or (is_bold and len(text) < 60):
                        block_output_strings.append(f"\n### {text}\n")
                    elif list_match:
                        # Clean lists into standard Markdown formats
                        item_content = list_match.group(3)
                        block_output_strings.append(f"- {item_content}")
                    else:
                        block_output_strings.append(text)

                if block_output_strings:
                    # Join lines together cleanly based on list structural properties
                    if any(s.startswith("- ") for s in block_output_strings):
                        markdown_document_output.append("\n".join(block_output_strings))
                    else:
                        markdown_document_output.append(" ".join(block_output_strings))

        return "\n\n".join(markdown_document_output)